name: CD-PAGES

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-and-sonar:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      working-directory: ./2023.1.devops-pre-hackathon

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: npm install

      - name: Run the tests
        working-directory: ${{env.working-directory}}
        run: npm run test -- --coverage
        env:
          CI: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      working-directory: ./2023.1.devops-pre-hackathon

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: npm install

      - name: Run the tests
        working-directory: ${{env.working-directory}}
        run: npm run test -- --coverage
        env:
          CI: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build the application
        working-directory: ${{env.working-directory}}
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '2023.1.devops-pre-hackathon/build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
